# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: "3.9"

services:
  postgres:
    image: postgres:15.0-alpine3.16
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432
    volumes:
      - ./docker/dbdata:/var/lib/postgresql/data
  api:
    image: api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/app/
      - node_modules:/app/node_modules/
    depends_on:
      - postgres

volumes:
  node_modules:
